syntax="proto3";

package proto;

option go_package = "./proto";

import "google/protobuf/timestamp.proto";

enum TaskStatus {
  TASK_STATUS_UNSPECIFIED = 0;
  TASK_STATUS_TODO = 1;
  TASK_STATUS_IN_PROGRESS = 2;
  TASK_STATUS_DONE = 3;
}

message Task {
  int32 id = 1;
  string title = 2;
  string description = 3;
  TaskStatus completion_status = 4;
  google.protobuf.Timestamp timestamp = 5;
}


// Endpoints:
message GetTaskRequest {
  int32 id = 1;
}

message AddTaskRequest {
  Task task = 1;
}

message Empty {}

message TaskList {
  repeated Task tasks = 1;
}

// Defining a service:

service TaskService {
  rpc GetTask(GetTaskRequest) returns (Task); // remote callable func called GetTask
  rpc ListTasks(Empty) returns (TaskList); 
  rpc AddTask(AddTaskRequest) returns (Task);
}
